server:
  port: 8090

spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        title: "CodeSync Live Admin"

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
