server:
  port: 8087

spring:
  application:
    name: comment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /comments/v3/api-docs
  swagger-ui:
    path: /comments/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

