server:
  port: 8083

spring:
  application:
    name: file-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # max size of a single uploaded file
      max-request-size: 15MB   # max size of the entire multipart request

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /files/v3/api-docs
  swagger-ui:
    path: /files/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: WARN
    com.codesync: INFO

